"""initial_schema

Revision ID: 0a08b8dbed80
Revises: 
Create Date: 2017-09-10 14:49:23.805119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a08b8dbed80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create extension pgcrypto")
    op.create_table('users',
                    sa.Column(
                        'user_id',
                        postgresql.UUID(),
                        server_default=sa.text('gen_random_uuid()'),
                        nullable=False),
                    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
                    sa.Column(
                        'password', sa.VARCHAR(length=128), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('user_id'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('confirmation',
                    sa.Column(
                        'confirm_id',
                        postgresql.UUID(),
                        server_default=sa.text('gen_random_uuid()'),
                        nullable=False),
                    sa.Column('user_id', postgresql.UUID(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('expires', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('confirm_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmation')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
