"""add table conf

Revision ID: 545559f028ec
Revises: f08106f34456
Create Date: 2017-08-05 15:58:52.324817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545559f028ec'
down_revision = 'f08106f34456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmation',
    sa.Column('conf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conf', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conf_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmation')
    # ### end Alembic commands ###
