"""created tables users and confirmation

Revision ID: 7df1554c82f8
Revises: 
Create Date: 2017-08-20 21:41:01.146241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7df1554c82f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create extension pgcrypto;")
    op.create_table('users',
                    sa.Column(
                        'user_id',
                        postgresql.UUID(),
                        server_default=sa.text('gen_random_uuid()'),
                        nullable=False),
                    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
                    sa.Column(
                        'password', sa.VARCHAR(length=128), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('user_id'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('confirmation',
                    sa.Column(
                        'conf_id',
                        postgresql.UUID(),
                        server_default=sa.text('gen_random_uuid()'),
                        nullable=False),
                    sa.Column('user_id', postgresql.UUID(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('expires', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'],
                        ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('conf_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmation')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
