"""adde acc

Revision ID: fd33483d40ed
Revises: 
Create Date: 2017-08-05 11:40:00.585723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd33483d40ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('login', sa.VARCHAR(length=16), nullable=True),
                    sa.Column('password', sa.VARCHAR(
                        length=24), nullable=True),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
